apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch-frontend
  namespace: gqms
  labels:
    app: hoppscotch-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoppscotch-frontend
  template:
    metadata:
      labels:
        app: hoppscotch-frontend
    spec:
      containers:
        - name: hoppscotch-frontend
          image: hoppscotch/hoppscotch-frontend
          envFrom:
            - configMapRef:
                name: hoppscotch
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch-admin
  namespace: gqms
  labels:
    app: hoppscotch-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoppscotch-admin
  template:
    metadata:
      labels:
        app: hoppscotch-admin
    spec:
      containers:
        - name: hoppscotch-admin
          image: hoppscotch/hoppscotch-admin
          envFrom:
            - configMapRef:
                name: hoppscotch
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch-backend
  namespace: gqms
  labels:
    app: hoppscotch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoppscotch-backend
  template:
    metadata:
      labels:
        app: hoppscotch-backend
    spec:
      containers:
        - name: hoppscotch-backend
          image: hoppscotch/hoppscotch-backend
          envFrom:
            - configMapRef:
                name: hoppscotch
          ports:
            - name: http
              containerPort: 3170
              protocol: TCP

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoppscotch-postgres
  namespace: gqms
  labels:
    app: hoppscotch-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoppscotch-postgres
  template:
    metadata:
      labels:
        app: hoppscotch-postgres
    spec:
      containers:
        - name: hoppscotch-postgres
          image: postgres:15-bullseye
          envFrom:
            - configMapRef:
                name: hoppscotch
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hoppscotch-pvc

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gqms
  name: hoppscotch-pvc
  labels:
    app: hoppscotch-postgres
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi


