apiVersion: v1
kind: Service
metadata:
  name: hoppscotch-frontend-svc
  namespace: gqms
  labels:
    app: hoppscotch-frontend
spec:
  ports:
    - name: hoppscotch-frontend-svc
      port: 3000
      targetPort: 3000
      protocol: TCP
      
  selector:
    app: hoppscotch-frontend